# Generated by Django 4.1.5 on 2023-01-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('inputs', models.TextField()),
                ('output', models.TextField()),
            ],
        ),
    ]
